export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENT_BY_VALUE = 'INCREMENT_BY_VALUE';
export const DECREMENT_BY_VALUE = 'DECREMENT_BY_VALUE';
export const STORE_RESULT = 'STORE_RESULT';
export const DELETE_RESULT = 'DELETE_RESULT';
